### ISSUE TITLE
292 n-words when only 2 actually found

### ISSUE THREAD

**Issue by Sivat394** [alashow/wordscounterbot#1]
https://www.reddit.com/r/SmugIdeologyMan/comments/hipn9t/its_high_time_to_repost_this_classic/fwj6oeu/

I dunno exactly what caused it but it should only be reporting 2 not 292 poor dude got blindsided by that count.

**Comment by alashow** [comment]
It's coming from a submission they deleted a year ago: http://api.pushshift.io/reddit/search/submission/?ids=cn2wmq

Currently, the bot attaches a link to scanned comments from Pushshift. You can ask the bot to fetch more links to get links for matching submissions.

**Comment by Sivat394** [comment]
You should have the deleted posts included in the initial pushshift link if that's the case. Why should someone have to ask for more links? 

https://api.pushshift.io/reddit/search/comment/?ids=epvz4m3,epfaivf is the only thing that gets shown

**Comment by alashow** [comment]
To not to clutter responses. I would have to add another link to give the submissions link. So I decided to only add comments link by default, might change it later.

Also, this kind of response (high count but only 2 comments scanned) happens rarely and implies spam.
